version: '3.7'

networks:
  web_xdjango:

volumes:
  datavolume:
  static:
  acme:
  .:

services:
  
  db:
    image: postgres:14.4
    container_name: xdjango_db
    ports:
      - 5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - datavolume:/var/lib/postgresql/data
    networks:
      web_xdjango:
    restart: always

  app:
    build:
      context: .
    volumes:
      - static:/app/static
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      web_xdjango:
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./nginx:/etc/nginx/conf.d
      # - static:/app/static
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    depends_on:
      - app
    networks:
      web_xdjango:
    # labels:
      # - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy


  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./certs:/etc/nginx/certs:ro
  #     - acme:/etc/acme.sh
  #   volumes_from:
  #     - nginx-proxy:ro
    

  nginx:
    build: ./nginx
    expose:
      - "80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/app/static
    # environment:
    #   - VIRTUAL_HOST=vallesmarket.com,www.vallesmarket.com
    #   - LETSENCRYPT_HOST=vallesmarket.com,www.vallesmarket.com
    #   - LETSENCRYPT_EMAIL=siriusx711@gmail.com
    networks:
      web_xdjango:
    restart: always